development:
  adapter: postgres
  user: postgres
  host: localhost
  port: 5432
  database: crab_core

test:
  adapter: postgres
  user: postgres
  host: localhost
  port: 5432
  database: crab_core_test

production:
  adapter: postgres
  user: 'iwywirpvrutazo:630db5fd6c47cac81cc40a59d455517acfd150976b53ea2d7517d3d456a876b5'
  host: 'ec2-184-72-216-69.compute-1.amazonaws.com'
  port: 5432
  database: 'd89m2tqnmgkrrh'
